name: wombat-pipelines
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - flashlfq=1.1.1
  - pandas
  - thermorawfileparser=1.3.4
  - searchgui=4.0.33
  - peptide-shaker=2.0.25
  - unzip=6.0 
  - bioconductor-preprocesscore=1.56.0
  - bioconductor-msnbase=2.20.0
  - r-msqrob=0.7.7
  - r-matrixstats
  - git
  - pip
  - r-hexbin
  - pyyaml=5.4.1
  - r-stringi=1.7.6
  - r-matrixstats=0.62.0
  - r-stringr=1.4.0
  - r-jsonlite=1.8.0
  - dotnet
  - maxquant=2.0.3.0
  - unzip=6.0
  - polystest=1.01
  - r-stringi=1.7.6
  - r-matrixstats=0.62.0
  - r-stringr=1.4.0
  - r-jsonlite=1.8.0
  - comet-ms=2019015
  - r-progress=1.2.2
  - r-dplyr=1.0.9
  - r-xml=3.99-0.10
  - pyteomics=4.5.3
  - bioconductor-limma=3.50.1
  - bioconductor-rots=1.22.0
  - bzip2 1.0*
  - hardklor
  - libgcc <=4.9
  - perl 5.22.0*
  - perl-findbin-libs
  - perl-xml-parser
  - zlib 1.2.11*
  - libgomp
  - future
